#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

git pull origin master
npm install --prefix client
npm install --prefix server
npm run build --prefix client
cp -r ~/ChatApp/client/dist/. /var/www/chatapp.liborb.com/
pm2 stop index
pm2 start server/index.js
